version: "3.8"
networks:
  test:

services:
  java:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - test

  db:
    platform: linux/x86_64
    image: hayond/h2database:latest
    container_name: db
    ports:
      - "13306:3306"
    volumes:
        - ./data:/opt/h2-data
        - ./setup.sql:/opt/h2-data/setup.sql
    restart: always
    networks:
      - test